language: php

php:
  - 5.3
  - 5.4

services:
  - elasticsearch

before_script:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit --coverage-text
